### PR TITLE
Set default (global) tolerance to 1.e-14

### PR DESCRIPTION
**Pull request by MaxThevenet**

### CODE REVIEW

**Comment by atmyers** [comment]
This won't solve the issue on battra though, since I don't know that we want to set a global tolerance for all codes, instead of just WarpX

**Comment by MaxThevenet** [comment]
Oh wait, Battra tests are not using this repo?

**Comment by atmyers** [comment]
This is a fork of the AMReX/regression_testing repo that (I believe) is only used when running the WarpX tests through Travis CI.

**Comment by MaxThevenet** [comment]
Thanks, then this PR is useless, I'll close it.

**Pull request closed without merging**
